import type { Metadata, Viewport } from "next";
import "./globals.css";

// Runs before paint to apply the saved (or system) theme and avoid a flash.
const themeInitScript = `
(function () {
  try {
    var t = localStorage.getItem('theme');
    var dark = t ? t === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches;
    if (dark) document.documentElement.classList.add('dark');
  } catch (e) {}
})();
`;

export const metadata: Metadata = {
  title: "LLM User Interface",
  description: "Generated by create next app",
};

// Keep pinch-zoom enabled for accessibility (no maximumScale/userScalable).
// `themeColor` colors the mobile browser chrome to match each theme's
// `--background` (see globals.css).
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased"
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="h-dvh flex flex-col">{children}</body>
    </html>
  );
}
